name: build-and-test

on:
  push:

jobs:
  build-and-test-linux:
    name: Build & Test (Node v${{ matrix.node-version }}, Ubuntu 18.04)

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish Packages (Beta Channel)
        if: matrix.node-version == '14.x' && github.ref == 'refs/heads/beta'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          lerna publish --yes --dist-tag beta

      - name: Make analyzer-gui .deb
        if: matrix.node-version == '14.x'
        run: yarn make:deb
        working-directory: packages/analyzer-gui

      - name: Upload analyzer-gui .deb
        if: matrix.node-version == '14.x'
        uses: actions/upload-artifact@v2
        with:
          name: analyzer-gui-deb
          path: packages/analyzer-gui/out/make/deb/x64/*.deb

  build-macos:
    name: Build (Node v${{ matrix.node-version }}, MacOS)

    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Make analyzer-gui .dmg
        if: matrix.node-version == '14.x'
        run: yarn make:dmg
        working-directory: packages/analyzer-gui

      - name: Upload analyzer-gui .dmg
        if: matrix.node-version == '14.x'
        uses: actions/upload-artifact@v2
        with:
          name: analyzer-gui-dmg
          path: packages/analyzer-gui/out/make/*.dmg
