name: build-and-test

on:
  push:

jobs:
  build-and-test:
    name: Build & Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  package-gui-deb:
    name: analyzer-gui - Package .deb

    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Make .deb
        run: yarn make:deb
        working-directory: packages/analyzer-gui

      - name: Upload .deb
        uses: actions/upload-artifact@v1
        with:
          name: analyzer-gui-deb
          path: packages/analyzer-gui/out/make/deb/x64/*.deb
